version: '3'
services: 
    theairclassclient : 
        build: .
        ports: 
            - 8081:8081
        volumes: 
            - .:/user/scr/app/
networks: 
    default :
        external: 
            name:  theairclassclient-network